### PR TITLE
Fullcalendar v3

### PR DESCRIPTION
**Pull request by julienmalik**
Integrate fullcalendar 3.0.0-beta, which supports week numbers.
Add weekNumbers in all views.

I think it deserves a specific user preference, but I'm publishing this PR in the hope to get a first feedback.

### CODE REVIEW

**Comment by julienmalik** [comment]
Now it can be enabled/disabled in the preference view.

**Comment by julienmalik** [comment]
fullcalendar 3.0.0 is now released.
Rebased this branch onto latest develop

**Comment by julienmalik** [comment]
hey @adobo ! any opinion on this ?

**Comment by adobo** [comment]
You did an impressive work there, @julienmalik! I was thinking about keeping this update for later releases, but using a much newer Fullcalendar makes sense for AgenDAV 2.0.0, so let's go for it.

With some changes I would merge it inmediately:

* CHANGELOG should definitely mention this
* A note about IE8 not being supported anymore would be great too
* IMO keeping the week numbers off by default would be better

Thank you!

**Comment by julienmalik** [comment]
Rebased on develop, and addressed all 3 remarks

**Comment by adobo** [comment]
Thank you very much @julienmalik !

**Pull request merged**
