### PR TITLE
Update Symfony to 2.8

### PR DESCRIPTION
**Pull request by mmoll**
I did some housekeeping before really going to Symfony 2.8 to ensure PHP 5.4 compatibility.

### CODE REVIEW

**Comment by mmoll** [comment]
BTW, are there any plans to move the PHP requirement to 5.5 or even 5.6?

**Comment by adobo** [comment]
@mmoll this PR is really great! Thank you very much.

I'm actually considering bumping the PHP version to 5.5. Do you have any suggestions about which patch level should be required at least?

**Comment by mmoll** [comment]
Not really, as e.g. in Ubuntu/trusty there's 5.5.9, but patched at least with security updates, maybe even bugfixes, so it's hard to really set a specific patch level as baseline.

BTW, a 2.0.0-beta2 release would be nice for PHP7 support.

**Comment by adobo** [comment]
@mmoll do you think additional dependency changes are required for a PHP7 compatible release?

I tried latest HEAD with PHP 7 with no issues at all.

**Comment by mmoll** [comment]
From all I can say, the are no PHP7 incompatible parts left, I'm also running on 7 since about three weeks and seeing no issues.

**Comment by adobo** [comment]
Great! Same experience here with PHP 7.

I have opened #165 to talk about PHP 5.5.

**Pull request merged**
